wandb_version: 1

alpha_balance:
  value: 0.030908714519886585
batch_size:
  value: 16
context_window:
  value: 128
dim:
  value: 256
dropout_rate:
  value: 0.1
epochs:
  value: 6
expansion:
  value: 4
grad_accum:
  value: 2
kv_heads:
  value: 2
lr:
  value: 0.00014592039071624317
max_context:
  value: 512
n_experts:
  value: 4
no_sink:
  value: true
num_blocks:
  value: 4
optimizer:
  value: adamw
pos_encoding:
  value: trainable
sliding_window:
  value: false
tokenizer_type:
  value: bpe
top_k_mlp:
  value: 2
use_moe:
  value: false
warmup_steps:
  value: 50
weight_tying:
  value: true
