absolute_pos: false
activation: gelu
batch_size: 128
context_window: 32
dataset_name: Daniele/dante-corpus
dataset_source: huggingface
dim: 512
epochs: 1000
eval_iters: 20
expansion: 4
grad_accum: 16
gradient_checkpointing: true
head_size: 32
kv_heads: 4
log_file: training_log.csv
lr: 0.005
max_context: 512
n_experts: 4
n_heads: 16
no_sink: true
num_blocks: 16
optimizer: adamw
seed: 42
sliding_window: false
streaming: true
summary_file: model_summary.json
tokenizer_path: configs/vocab.json
tokenizer_type: bpe
top_k_mlp: 2
trainable_pos: false
use_moe: false
use_rotary_pos: true
vocab_size: 5000
warmup_steps: 420
weight_tying: true
