wandb_version: 1

alpha_balance:
  value: 0.041536715340009654
batch_size:
  value: 64
context_window:
  value: 64
dim:
  value: 256
dropout_rate:
  value: 0.1
epochs:
  value: 8
expansion:
  value: 2
grad_accum:
  value: 4
kv_heads:
  value: 4
lr:
  value: 0.00026188889794386764
max_context:
  value: 512
n_experts:
  value: 4
no_sink:
  value: true
num_blocks:
  value: 12
optimizer:
  value: adafactor
pos_encoding:
  value: absolute
sliding_window:
  value: true
tokenizer_type:
  value: char
top_k_mlp:
  value: 2
use_moe:
  value: true
warmup_steps:
  value: 200
weight_tying:
  value: true
