wandb_version: 1

alpha_balance:
  value: 0.09305809998641368
batch_size:
  value: 64
context_window:
  value: 128
dim:
  value: 512
dropout_rate:
  value: 0.1
epochs:
  value: 12
expansion:
  value: 4
grad_accum:
  value: 8
kv_heads:
  value: 4
lr:
  value: 0.0028100321896800543
max_context:
  value: 256
n_experts:
  value: 4
no_sink:
  value: true
num_blocks:
  value: 4
optimizer:
  value: adafactor
pos_encoding:
  value: absolute
sliding_window:
  value: false
tokenizer_type:
  value: char
top_k_mlp:
  value: 1
use_moe:
  value: true
warmup_steps:
  value: 200
weight_tying:
  value: true
