wandb_version: 1

alpha_balance:
  value: 0.09408947599192484
batch_size:
  value: 64
context_window:
  value: 32
dim:
  value: 256
dropout_rate:
  value: 0.1
epochs:
  value: 16
expansion:
  value: 4
grad_accum:
  value: 4
kv_heads:
  value: 4
lr:
  value: 0.0005973022854895319
max_context:
  value: 256
n_experts:
  value: 4
no_sink:
  value: false
num_blocks:
  value: 12
optimizer:
  value: adamw
pos_encoding:
  value: rotary
sliding_window:
  value: true
tokenizer_type:
  value: char
top_k_mlp:
  value: 2
use_moe:
  value: false
warmup_steps:
  value: 200
weight_tying:
  value: false
