wandb_version: 1

alpha_balance:
  value: 0.020908655766959085
batch_size:
  value: 64
context_window:
  value: 128
dim:
  value: 512
dropout_rate:
  value: 0.15
epochs:
  value: 16
expansion:
  value: 4
grad_accum:
  value: 8
kv_heads:
  value: 4
lr:
  value: 0.0005543777370988281
max_context:
  value: 256
n_experts:
  value: 4
no_sink:
  value: false
num_blocks:
  value: 12
optimizer:
  value: adafactor
pos_encoding:
  value: rotary
sliding_window:
  value: false
tokenizer_type:
  value: char
top_k_mlp:
  value: 2
use_moe:
  value: false
warmup_steps:
  value: 100
weight_tying:
  value: true
