wandb_version: 1

alpha_balance:
  value: 0.11957902980997152
batch_size:
  value: 64
context_window:
  value: 64
dim:
  value: 512
dropout_rate:
  value: 0.15
epochs:
  value: 20
expansion:
  value: 2
grad_accum:
  value: 2
kv_heads:
  value: 2
lr:
  value: 0.0039377589732294
max_context:
  value: 512
n_experts:
  value: 4
no_sink:
  value: true
num_blocks:
  value: 12
optimizer:
  value: adafactor
pos_encoding:
  value: absolute
sliding_window:
  value: true
tokenizer_type:
  value: char
top_k_mlp:
  value: 2
use_moe:
  value: false
warmup_steps:
  value: 50
weight_tying:
  value: false
