wandb_version: 1

alpha_balance:
  value: 0.0922513818370583
batch_size:
  value: 64
context_window:
  value: 32
dim:
  value: 512
dropout_rate:
  value: 0.15
epochs:
  value: 12
expansion:
  value: 2
grad_accum:
  value: 2
kv_heads:
  value: 4
lr:
  value: 0.0014313117563223387
max_context:
  value: 512
n_experts:
  value: 4
no_sink:
  value: true
num_blocks:
  value: 12
optimizer:
  value: lion
pos_encoding:
  value: absolute
sliding_window:
  value: false
tokenizer_type:
  value: char
top_k_mlp:
  value: 1
use_moe:
  value: true
warmup_steps:
  value: 100
weight_tying:
  value: false
