wandb_version: 1

alpha_balance:
  value: 0.051586087294060265
batch_size:
  value: 16
context_window:
  value: 128
dim:
  value: 256
dropout_rate:
  value: 0
epochs:
  value: 24
expansion:
  value: 4
grad_accum:
  value: 4
kv_heads:
  value: 4
lr:
  value: 0.002360182339120145
max_context:
  value: 512
n_experts:
  value: 4
no_sink:
  value: false
num_blocks:
  value: 8
optimizer:
  value: adamw
pos_encoding:
  value: rotary
sliding_window:
  value: false
tokenizer_type:
  value: char
top_k_mlp:
  value: 2
use_moe:
  value: false
warmup_steps:
  value: 100
weight_tying:
  value: false
