wandb_version: 1

alpha_balance:
  value: 0.12636523887769535
batch_size:
  value: 16
context_window:
  value: 128
dim:
  value: 512
dropout_rate:
  value: 0.1
epochs:
  value: 12
expansion:
  value: 4
grad_accum:
  value: 4
kv_heads:
  value: 4
lr:
  value: 0.002318222767097123
max_context:
  value: 512
n_experts:
  value: 4
no_sink:
  value: true
num_blocks:
  value: 12
optimizer:
  value: adamw
pos_encoding:
  value: rotary
sliding_window:
  value: false
tokenizer_type:
  value: char
top_k_mlp:
  value: 1
use_moe:
  value: true
warmup_steps:
  value: 200
weight_tying:
  value: false
