wandb_version: 1

alpha_balance:
  value: 0.06818430266044256
batch_size:
  value: 64
context_window:
  value: 128
dim:
  value: 256
dropout_rate:
  value: 0.15
epochs:
  value: 12
expansion:
  value: 2
grad_accum:
  value: 2
kv_heads:
  value: 4
lr:
  value: 0.0018204586929266736
max_context:
  value: 512
n_experts:
  value: 4
no_sink:
  value: false
num_blocks:
  value: 12
optimizer:
  value: adafactor
pos_encoding:
  value: absolute
sliding_window:
  value: false
tokenizer_type:
  value: char
top_k_mlp:
  value: 2
use_moe:
  value: true
warmup_steps:
  value: 200
weight_tying:
  value: false
