wandb_version: 1

alpha_balance:
  value: 0.08482191175803833
batch_size:
  value: 64
context_window:
  value: 64
dim:
  value: 256
dropout_rate:
  value: 0
epochs:
  value: 12
expansion:
  value: 4
grad_accum:
  value: 4
kv_heads:
  value: 4
lr:
  value: 0.0026989071529000216
max_context:
  value: 512
n_experts:
  value: 4
no_sink:
  value: false
num_blocks:
  value: 12
optimizer:
  value: adafactor
pos_encoding:
  value: absolute
sliding_window:
  value: true
tokenizer_type:
  value: char
top_k_mlp:
  value: 2
use_moe:
  value: false
warmup_steps:
  value: 100
weight_tying:
  value: false
