program: train_sweep.py
method: random
metric:
  name: val_loss
  goal: minimize
parameters:
  epochs:
    values: [24]
  optimizer:
    values: ["adamw", "adafactor", "lion"]
  tokenizer_type:
    values: ["char", "bpe"]
  max_context:
    values: [128, 192, 256, 384, 512] 
  weight_tying:
    values: [true, false]
  dropout_rate:
    distribution: uniform 
    min: 0.0
    max: 0.3
  lr:
    distribution: log_uniform_values
    min: 0.00001 
    max: 0.02    
  batch_size:
    values: [8, 16, 24, 32, 48, 64] 
  grad_accum:
    values: [1, 2, 3, 4, 6, 8]
  warmup_steps:
    distribution: int_uniform 
    min: 0
    max: 300
  dim:
    values: [128, 192, 256, 384, 512, 768] 
  num_blocks:
    values: [4, 6, 8, 10, 12, 14, 16, 20] 
  kv_heads:
    values: [1, 2, 4, 8]
  use_moe:
    values: [true, false]
  n_experts:
    values: [2, 4, 6, 8, 12, 16]
  top_k_mlp:
    values: [1, 2, 3, 4]
  expansion:
    values: [2, 4, 6, 8]
  alpha_balance:
    distribution: uniform 
    min: 0.001
    max: 0.3
  sliding_window:
    values: [true]
  context_window:
    values: [16, 32, 48, 64, 96, 128, 192]
  no_sink:
    values: [true, false]
  pos_encoding:
    values: ["rotary", "absolute"]
  use_swiglu:
    values: [true, false]
command:
  - ${env}
  - python
  - ${program}
  - ${args}