absolute_pos: false
activation: gelu
alpha_balance: 0.025564518055671694
batch_size: 32
context_window: 64
dataset_name: Daniele/dante-corpus
dataset_source: huggingface
dim: 512
dropout_rate: 0
epochs: 16
eval_iters: 20
expansion: 4
grad_accum: 2
gradient_checkpointing: true
head_size: 32
kv_heads: 4
log_file: training_log.csv
lr: 0.0003697500800062656
max_context: 512
n_experts: 4
n_heads: 16
no_sink: true
num_blocks: 8
optimizer: adafactor
seed: 42
sliding_window: true
streaming: true
summary_file: model_summary.json
tokenizer_path: configs/vocab.json
tokenizer_type: char
top_k_mlp: 2
trainable_pos: false
use_moe: true
use_rotary_pos: true
vocab_size: 2000
warmup_steps: 200
weight_tying: false
